version: '3.4'

services:
  consul:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8500:8500"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./init/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./init/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      #- ./init/tempo-data:/tmp/tempo
    ports:
      - "14268"
      - "9411:9411"

  loki:
    image: grafana/loki
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./init/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./init/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./init/grafana/dashboards:/var/lib/grafana/dashboards
      #- ./init/grafana/data:/var/lib/grafana