spring:
  zipkin:
    baseUrl: http://localhost:9411

logging:
  level:
    ROOT: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1